import './globals.css'
import './Calendar.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/layouts/Header'
import Footer from '@/components/layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // Suggest using theme-change: https://github.com/saadeghi/theme-change
    <html lang="en" data-theme="dark">
      <body className={`${inter.className} bg-neutral min-h-screen prose-h1:text-lg prose-h2:text-md`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
